# Generated by Django 3.0.8 on 2020-08-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passout_year', models.IntegerField()),
                ('current_status', models.CharField(choices=[('Higher studies', 'Higher studies'), ('Job', 'Job'), ('Entrepreneurship', 'Entrepreneurship')], max_length=20)),
                ('programme', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('interview_ques', models.CharField(max_length=1000)),
                ('startup_name', models.CharField(max_length=100)),
                ('startup_description', models.CharField(max_length=5000)),
                ('books', models.CharField(max_length=500)),
                ('additional_tips', models.CharField(max_length=5000)),
                ('advice', models.CharField(max_length=5000)),
                ('contact', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Email', 'Email')], max_length=100)),
            ],
        ),
    ]
