# Generated by Django 3.0.8 on 2020-08-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_response', '0002_auto_20200802_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='additional_tips',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='advice',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='books',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='contact',
            field=models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Email', 'Email')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='interview_ques',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='profile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='programme',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='startup_description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='startup_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
