# Generated by Django 3.0.3 on 2020-08-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_response', '0004_auto_20200803_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='passout_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
