# Generated by Django 3.0.3 on 2020-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_response', '0006_auto_20200803_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
