# Generated by Django 3.0.3 on 2020-08-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_response', '0007_response_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='department',
            field=models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Science and Technology', 'Chemical Science and Technology'), ('Chemical Engineering', 'Chemical Engineering'), ('Biotech', 'Biotech'), ('Engineering Physics', 'Engineering Physics'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering')], max_length=50, null=True),
        ),
    ]
