# Generated by Django 3.0.3 on 2020-08-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_response', '0008_response_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='current_job',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
