# Generated by Django 3.0.3 on 2020-08-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_response', '0009_response_current_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='alumni',
        ),
    ]
