# Generated by Django 3.0.3 on 2020-08-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_response', '0011_response_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.CharField(max_length=5000, null=True)),
                ('contact', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Email', 'Email')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Higher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=100, null=True)),
                ('university', models.CharField(max_length=100, null=True)),
                ('books', models.CharField(max_length=500, null=True)),
                ('additional_tips', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('interview_ques', models.CharField(max_length=1000, null=True)),
                ('books', models.CharField(max_length=500, null=True)),
                ('additional_tips', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Start_Up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=100, null=True)),
                ('startup_description', models.CharField(max_length=5000, null=True)),
                ('books', models.CharField(max_length=500, null=True)),
                ('additional_tips', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='response',
            name='additional_tips',
        ),
        migrations.RemoveField(
            model_name='response',
            name='advice',
        ),
        migrations.RemoveField(
            model_name='response',
            name='books',
        ),
        migrations.RemoveField(
            model_name='response',
            name='company',
        ),
        migrations.RemoveField(
            model_name='response',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='response',
            name='interview_ques',
        ),
        migrations.RemoveField(
            model_name='response',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='response',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='response',
            name='startup_description',
        ),
        migrations.RemoveField(
            model_name='response',
            name='startup_name',
        ),
        migrations.RemoveField(
            model_name='response',
            name='university',
        ),
    ]
