# Generated by Django 3.0.3 on 2020-08-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_response', '0014_auto_20200809_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('MNC', 'Mathematics and Computing'), ('EEE', 'Electronics and Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('Civil', 'Civil Engineering'), ('CST', 'Chemical Science and Technology'), ('CE', 'Chemical Engineering'), ('BT', 'Biotech'), ('EP', 'Engineering Physics'), ('ECE', 'Electronics and Communication Engineering')], max_length=50, null=True),
        ),
    ]
