# Generated by Django 3.0.3 on 2020-08-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_response', '0016_auto_20200809_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni_response.Response'),
        ),
        migrations.AddField(
            model_name='higher',
            name='response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni_response.Response'),
        ),
        migrations.AddField(
            model_name='job',
            name='response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni_response.Response'),
        ),
        migrations.AddField(
            model_name='start_up',
            name='response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni_response.Response'),
        ),
    ]
